When importing zoo rather than fully loading it, it may sometimes be preferable to have S3 methods always registered with one of the generics. Even in those cases where the methods had been fully exported in order to be accessible to _all_ conceivable generics.
Hence, all methods that had previously been fully exported
(merge.zoo, MATCH.default, ..., and many more) are now additionally
registered as S3method()s.

Exception: as.Date.* are still only fully exported.



git-svn-id: svn://svn.r-forge.r-project.org/svnroot/zoo@952 edb9625f-4e0d-4859-8d74-9fd3b1da38cb